"""nova alteração

Revision ID: 928a38ba8345
Revises: c2c61ffa10b2
Create Date: 2026-02-05 01:20:48.589834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '928a38ba8345'
down_revision = 'c2c61ffa10b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('perfil',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=22),
               existing_nullable=False)
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=240),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=240),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('perfil',
               existing_type=sa.String(length=22),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
