"""descrição clara

Revision ID: c2c61ffa10b2
Revises: 374218dbb31b
Create Date: 2026-02-05 01:08:34.330341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2c61ffa10b2'
down_revision = '374218dbb31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('senha',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('senha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('telefone')
        batch_op.drop_column('nascimento')
        batch_op.drop_column('matricula')
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
