"""Criar tabela Projeto

Revision ID: c917cccf0137
Revises: 928a38ba8345
Create Date: 2026-02-05 12:53:23.424770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c917cccf0137'
down_revision = '928a38ba8345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('edital', sa.String(length=100), nullable=True),
    sa.Column('nome_projeto', sa.String(length=150), nullable=False),
    sa.Column('imagem', sa.String(length=150), nullable=True),
    sa.Column('coordenador', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_projeto', sa.Date(), nullable=False),
    sa.Column('tipo_projeto', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    # ### end Alembic commands ###
